package com.baidu.dao;

import com.baidu.bean.Person;
import com.baidu.bean.PersonExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    Person selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated Fri Jun 28 19:20:10 CST 2019
     */
    int updateByPrimaryKey(Person record);
}